/** @format */

/**
 * SAMPLE
 */

export const products = [
  {
    id: '1',
    title: 'MOONDROP PSYCHE',
    subtitle: '2DD + 4BA + 4Planar In-ear Monitor',
    artist: 'Moondrop',
    category: 'IEM',
    price: 'Rp. 10,000,000.00',
    image: '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
    images: [
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
      '/a1f101c767fd4b8cc4d3d6367359ad617fa8ed1c.png',
    ],
    features: [
      'Hand-crafted MITSUKIYUKI faceplate',
      'Combination of Traditional Craft and Modern Art',
      'Exquisite Chinese Bronze Age Craftsmanship. Inlaid Gold and Silver.',
      'Rose gold and yellow gold are hand-inlaid into the grooves of the silver panel.',
      'Repeated cycles of engraving and polishing bring to life the image of MITSUKIYUKI, the maiden who overcame hardships to find true love and spiritual joy.',
      "Superb sound quality created by MOONDROP's many years of acoustic technology development.",
      'A unique collectible item that combines the essence of traditional craftsmanship, modern aesthetics and advanced technology.',
    ],
    specifications: [
      'Model: MOONDROP Psyche Reference In-ear Monitor',
      'Driver Configuration: Three-way Frequency Crossover 2DD+ 4BA+ 4PD',
      'Impedance: 17.5Ω±15% (@1kHz)',
      'Sensitive: 115dB / Vrms (@1kHz)',
      'THD: THD≤1% (@1kHz, 94dB)',
      'Frequency Response: 7Hz- 46kHz',
      'Effective Frequency Response: 20Hz 20kHz (IEC60318-4, 3dB)',
      'Socket: 0.78-2pin',
      'Plug: 4.4mm Fully Balanced Plug',
    ],
    package: [
      '1. Psyche',
      '2. Cable',
      '3. Storage Bag',
      '4. Anime Card',
      '5. Eartips (S, M, L)',
      '6. Manual',
      '7. Certificate',
      '8. Service Card',
    ],
  },
  {
    id: '2',
    title: 'THIEAUDIO MONARCH MK3',
    subtitle: '1DD + 2EST + 8BA Tribrid In-ear Monitor',
    artist: 'ThieAudio',
    category: 'IEM',
    price: 'Rp. 15,999,000.00',
    image: '/monarch-mk3.png',
    images: ['/monarch-mk3.png', '/monarch-mk3.png', '/monarch-mk3.png'],
    features: [
      'Tribrid driver configuration for exceptional clarity',
      '10mm dynamic driver for deep bass response',
      '2 Sonion electrostatic tweeters for ultra-high frequency extension',
      '8 Knowles balanced armatures for detailed mids',
      'Premium aluminum alloy CNC machined shell',
      'MMCX detachable cable system',
      'Reference-level tuning for critical listening',
    ],
    specifications: [
      'Model: THIEAUDIO Monarch MK3',
      'Driver Configuration: 1DD + 8BA + 2EST Tribrid',
      'Impedance: 13.8Ω (@1kHz)',
      'Sensitivity: 104dB/Vrms (@1kHz)',
      'Frequency Response: 10Hz - 40kHz',
      'Socket: MMCX',
      'Plug: 3.5mm + 4.4mm cables included',
    ],
    package: [
      '1. Monarch MK3 IEM',
      '2. 3.5mm Cable',
      '3. 4.4mm Cable',
      '4. Premium Carrying Case',
      '5. Eartips (S, M, L)',
      '6. Cleaning Tool',
    ],
  },
  {
    id: '3',
    title: 'TRUTHEAR HEXA',
    subtitle: 'Harman-Tuned 4BA + 1DD Hybrid IEM',
    artist: 'Truthear',
    category: 'IEM',
    price: 'Rp. 1,299,000.00',
    image: '/truthear-hexa.png',
    images: ['/truthear-hexa.png', '/truthear-hexa.png'],
    features: [
      'Harman-inspired target tuning',
      '10mm LCP dynamic driver for bass',
      '4 balanced armatures for mids and highs',
      'Affordable flagship killer performance',
      'Premium resin shell construction',
      'Comfortable ergonomic fit',
      'Detachable 0.78mm 2-pin cable',
    ],
    specifications: [
      'Model: Truthear HEXA',
      'Driver: 1DD + 4BA Hybrid',
      'Impedance: 20.5Ω',
      'Sensitivity: 120dB/Vrms',
      'Frequency Response: 20Hz - 20kHz',
      'Socket: 0.78mm 2-pin',
      'Plug: 3.5mm',
    ],
    package: [
      '1. HEXA IEM',
      '2. Silver-Plated Cable',
      '3. Eartips (S, M, L)',
      '4. Carrying Pouch',
      '5. Manual',
    ],
  },
  {
    id: '4',
    title: 'KIWI EARS QUINTET',
    subtitle: '1DD + 4BA Studio Reference Monitor',
    artist: 'Kiwi Ears',
    category: 'IEM',
    price: 'Rp. 2,450,000.00',
    image: '/kiwi-ears-quintet.png',
    images: ['/kiwi-ears-quintet.png'],
    features: [
      'Studio reference tuning for mixing and mastering',
      '10mm titanium-coated dynamic driver',
      '4 Knowles balanced armatures',
      'Wide soundstage and excellent imaging',
      '3D-printed medical-grade resin shell',
      'Exceptional build quality',
    ],
    specifications: [
      'Model: Kiwi Ears Quintet',
      'Driver: 1DD + 4BA Hybrid',
      'Impedance: 17Ω (@1kHz)',
      'Sensitivity: 108dB/mW',
      'Frequency Response: 20Hz - 20kHz',
      'Socket: 0.78mm 2-pin',
      'Plug: 4.4mm Balanced',
    ],
    package: [
      '1. Quintet IEM',
      '2. 4.4mm Cable',
      '3. Premium Case',
      '4. Multiple Eartips',
      '5. Cleaning Kit',
    ],
  },
  {
    id: '5',
    title: '7HZ TIMELESS AE',
    subtitle: '14.2mm Planar Magnetic Driver IEM',
    artist: '7Hz',
    category: 'IEM',
    price: 'Rp. 3,200,000.00',
    image: '/7hz-timeless-ae.png',
    images: ['/7hz-timeless-ae.png'],
    features: [
      'Large 14.2mm planar magnetic driver',
      'Ultra-low distortion and fast transient response',
      'Enhanced bass and treble extension',
      'CNC aluminum alloy shell',
      'Comfortable lightweight design',
      'Audiophile-grade sound quality',
    ],
    specifications: [
      'Model: 7Hz Timeless AE',
      'Driver: 14.2mm Planar Magnetic',
      'Impedance: 14.8Ω (@1kHz)',
      'Sensitivity: 104dB/Vrms',
      'Frequency Response: 5Hz - 40kHz',
      'Socket: 0.78mm 2-pin',
      'Plug: 3.5mm',
    ],
    package: [
      '1. Timeless AE',
      '2. OFC Cable',
      '3. Carrying Case',
      '4. Multiple Eartip Sets',
      '5. User Manual',
    ],
  },
  {
    id: '6',
    title: 'SENNHEISER IE 600',
    subtitle: 'Single 7mm TrueResponse Transducer',
    artist: 'Sennheiser',
    category: 'IEM',
    price: 'Rp. 11,500,000.00',
    image: '/sennheiser-ie600.png',
    images: ['/sennheiser-ie600.png'],
    features: [
      'Proprietary 7mm TrueResponse transducer',
      'Amorphous Zirconium housing for zero resonance',
      'Natural and detailed sound signature',
      'Compact ergonomic design',
      'Premium German engineering',
      'Detachable cable with MMCX-IE connector',
    ],
    specifications: [
      'Model: Sennheiser IE 600',
      'Driver: Single 7mm Dynamic',
      'Impedance: 18Ω',
      'Sensitivity: 118dB (1kHz/1Vrms)',
      'Frequency Response: 4Hz - 46.5kHz',
      'Socket: MMCX-IE',
      'Plug: 4.4mm Balanced',
    ],
    package: [
      '1. IE 600 Earphones',
      '2. Balanced Cable',
      '3. Premium Leather Case',
      '4. Silicone & Foam Tips',
      '5. Cleaning Tool',
    ],
  },
  {
    id: '7',
    title: 'DUNU SA6 MK2',
    subtitle: '6BA Modular Tuning System',
    artist: 'Dunu',
    category: 'IEM',
    price: 'Rp. 8,750,000.00',
    image: '/dunu-sa6-mk2.png',
    images: ['/dunu-sa6-mk2.png'],
    features: [
      '6 Knowles balanced armature drivers',
      'Modular atmospheric pressure balancing system',
      'Three tuning nozzles for customization',
      'High-precision 3-way crossover',
      'Premium patented QuickSwitch system',
      'Machined aluminum shell with stunning finish',
    ],
    specifications: [
      'Model: DUNU SA6 MK2',
      'Driver: 6BA Full Balanced Armature',
      'Impedance: 20Ω',
      'Sensitivity: 114dB/mW',
      'Frequency Response: 5Hz - 40kHz',
      'Socket: MMCX',
      'Plug: 4.4mm Balanced',
    ],
    package: [
      '1. SA6 MK2',
      '2. 3 Tuning Nozzles',
      '3. Premium Cable',
      '4. Leather Case',
      '5. Multiple Eartips',
      '6. Certificate',
    ],
  },
  {
    id: '8',
    title: 'CAMPFIRE AUDIO ANDROMEDA 2020',
    subtitle: '5BA Flagship In-ear Monitor',
    artist: 'Campfire Audio',
    category: 'IEM',
    price: 'Rp. 18,500,000.00',
    image: '/campfire-andromeda.png',
    images: ['/campfire-andromeda.png'],
    features: [
      '5 balanced armature drivers per side',
      'Legendary tuning with wide soundstage',
      'Hand-assembled in Portland, Oregon',
      'Premium stainless steel and aluminum chassis',
      'Beryllium PVD finish',
      'T.A.E.C. (Tuned Acoustic Expansion Chamber)',
    ],
    specifications: [
      'Model: Campfire Audio Andromeda 2020',
      'Driver: 5BA Full Balanced Armature',
      'Impedance: 12.8Ω (@1kHz)',
      'Sensitivity: 122.47dB SPL/mW',
      'Frequency Response: 10Hz - 28kHz',
      'Socket: MMCX',
      'Plug: 3.5mm',
    ],
    package: [
      '1. Andromeda IEM',
      '2. Silver-Plated Cable',
      '3. Premium Leather Case',
      '4. Final Audio Type E Tips',
      '5. Cleaning Tool',
      '6. Pin Tool',
    ],
  },
  {
    id: '9',
    title: 'SONY WH-1000XM5',
    subtitle: 'Premium Noise Cancelling Headphones',
    artist: 'Sony',
    category: 'Headphone',
    price: 'Rp. 5,499,000.00',
    image: '/sony-wh1000xm5.png',
    images: ['/sony-wh1000xm5.png'],
    features: [
      'Industry-leading noise cancellation',
      '30mm driver units for exceptional sound',
      '30-hour battery life',
      'Multipoint connection for seamless switching',
      'Speak-to-Chat technology',
      'Premium lightweight design with soft fit leather',
    ],
    specifications: [
      'Model: Sony WH-1000XM5',
      'Driver: 30mm Dynamic',
      'Frequency Response: 4Hz - 40kHz',
      'Battery Life: Up to 30 hours',
      'Bluetooth: 5.2 with LDAC support',
      'Weight: 250g',
      'Charging: USB-C',
    ],
    package: [
      '1. WH-1000XM5 Headphones',
      '2. Carrying Case',
      '3. USB-C Cable',
      '4. Audio Cable (3.5mm)',
      '5. Airplane Adapter',
      '6. User Manual',
    ],
  },
  {
    id: '10',
    title: 'FIIO FH7S',
    subtitle: '1DD + 4BA Hybrid Flagship IEM',
    artist: 'FiiO',
    category: 'IEM',
    price: 'Rp. 7,299,000.00',
    image: '/fiio-fh7s.png',
    images: ['/fiio-fh7s.png'],
    features: [
      '13.6mm beryllium-coated dynamic driver',
      '4 Knowles balanced armatures',
      'S.TURBO acoustic design',
      'Interchangeable tuning nozzles',
      'Premium CNC aluminum shell',
      'Detachable MMCX cable',
    ],
    specifications: [
      'Model: FiiO FH7S',
      'Driver: 1DD + 4BA Hybrid',
      'Impedance: 16Ω (@1kHz)',
      'Sensitivity: 111dB/mW',
      'Frequency Response: 5Hz - 40kHz',
      'Socket: MMCX',
      'Plug: 3.5mm',
    ],
    package: [
      '1. FH7S IEM',
      '2. MMCX Cable',
      '3. 3 Tuning Nozzles',
      '4. Leather Case',
      '5. Multiple Eartips',
    ],
  },
  {
    id: '11',
    title: 'AUDIO-TECHNICA ATH-M50X',
    subtitle: 'Professional Studio Monitor Headphones',
    artist: 'Audio-Technica',
    category: 'Headphone',
    price: 'Rp. 2,799,000.00',
    image: '/ath-m50x.png',
    images: ['/ath-m50x.png'],
    features: [
      '45mm large-aperture drivers',
      'Exceptional clarity and deep bass',
      'Professional studio standard',
      '90-degree swiveling earcups',
      'Collapsible design for easy storage',
      'Detachable cable system',
    ],
    specifications: [
      'Model: Audio-Technica ATH-M50X',
      'Driver: 45mm Dynamic',
      'Frequency Response: 15Hz - 28kHz',
      'Impedance: 38Ω',
      'Sensitivity: 99dB',
      'Weight: 285g',
      'Cable: 3 detachable cables included',
    ],
    package: [
      '1. ATH-M50X Headphones',
      '2. 3 Detachable Cables',
      '3. Carrying Pouch',
      '4. 1/4" Adapter',
    ],
  },
  {
    id: '12',
    title: 'SHURE SE846',
    subtitle: 'Quad High-Definition MicroDrivers',
    artist: 'Shure',
    category: 'IEM',
    price: 'Rp. 16,999,000.00',
    image: '/shure-se846.png',
    images: ['/shure-se846.png'],
    features: [
      'Four high-definition MicroDrivers',
      'True subwoofer low-pass filter',
      'Three interchangeable nozzle inserts',
      'Sound isolating design blocks 37dB',
      'Detachable cable with MMCX connector',
      'Professional touring-grade durability',
    ],
    specifications: [
      'Model: Shure SE846',
      'Driver: Quad Balanced Armature',
      'Impedance: 9Ω (@1kHz)',
      'Sensitivity: 114dB SPL/mW',
      'Frequency Response: 15Hz - 20kHz',
      'Socket: MMCX',
      'Plug: 3.5mm',
    ],
    package: [
      '1. SE846 Earphones',
      '2. Detachable Cable',
      '3. 3 Tuning Nozzles',
      '4. Multiple Eartips',
      '5. Hard Carrying Case',
      '6. Cleaning Tool',
    ],
  },
  {
    id: '13',
    title: 'FOCAL CLEAR MG',
    subtitle: 'Open-Back High-Fidelity Headphones',
    artist: 'Focal',
    category: 'Headphone',
    price: 'Rp. 22,500,000.00',
    image: '/focal-clear-mg.png',
    images: ['/focal-clear-mg.png'],
    features: [
      'M-shaped dome made from pure Magnesium',
      'Open-back design for natural soundstage',
      'Exceptional transparency and dynamics',
      'Memory foam ear cushions',
      'Premium leather headband',
      'Made in France',
    ],
    specifications: [
      'Model: Focal Clear Mg',
      'Driver: 40mm Full-range M-dome',
      'Impedance: 55Ω',
      'Sensitivity: 104dB SPL/1mW',
      'Frequency Response: 5Hz - 28kHz',
      'Weight: 450g',
      'Cable: 3m detachable',
    ],
    package: [
      '1. Clear Mg Headphones',
      '2. 2 Detachable Cables',
      '3. Hard Carrying Case',
      '4. 1/4" Adapter',
    ],
  },
  {
    id: '14',
    title: 'BLESSING 3',
    subtitle: '1DD + 4BA Tribrid IEM by Moondrop',
    artist: 'Moondrop',
    category: 'IEM',
    price: 'Rp. 4,999,000.00',
    image: '/blessing3.png',
    images: ['/blessing3.png'],
    features: [
      '10mm DLC diaphragm dynamic driver',
      '4 Knowles balanced armature drivers',
      'Harman-inspired tuning',
      'Premium resin shell with metal faceplate',
      'Ergonomic fit for long listening sessions',
      'Excellent value flagship killer',
    ],
    specifications: [
      'Model: Moondrop Blessing 3',
      'Driver: 1DD + 4BA Hybrid',
      'Impedance: 14.8Ω (@1kHz)',
      'Sensitivity: 117dB/Vrms',
      'Frequency Response: 10Hz - 35kHz',
      'Socket: 0.78mm 2-pin',
      'Plug: 3.5mm',
    ],
    package: [
      '1. Blessing 3 IEM',
      '2. Silver-Plated Cable',
      '3. Carrying Case',
      '4. Multiple Eartips',
      '5. User Manual',
    ],
  },
];

/**
 * Get product by ID
 * @param {string} id - Product ID
 * @returns {Object|null} - Product object or null if not found
 */
export function getProductById(id) {
  return products.find((p) => p.id === id) || null;
}

/**
 * Get all products
 * @returns {Array} - Array of all products
 */
export function getAllProducts() {
  return products;
}

/**
 * Get products by category
 * @param {string} category - Category name ('All', 'IEM', 'Headphone', 'Eartips')
 * @returns {Array} - Filtered array of products
 */
export function getProductsByCategory(category) {
  if (category === 'All') {
    return products;
  }
  return products.filter((p) => p.category === category);
}
